Added DateLocalization for dk
sql-bi/Bravo pull request #564
Opened 2022-12-22 09:34 UTC by mrSkovgaard

As suggested in @albertospelta 's answer to #563 I have added Danish translation for date table columns. I have translated column names in all DateLocalization files. Br, Niels

2022-12-22 13:22 UTC, albertospelta requested changes
Thanks for the PR! Would you mind applying the requested changes? 
It's just a small fix to the ISO language code.

2022-12-22 13:22 UTC, albertospelta commented on src/Assets/ManageDates/Templates/DateLocalization-01.json
> +      "Iso": "dk",
```suggestion
      "Iso": "da",
```

2022-12-22 13:22 UTC, albertospelta commented on src/Assets/ManageDates/Templates/DateLocalization-02.json
> +      "Iso": "dk",
```suggestion
      "Iso": "da",
```

2022-12-22 13:22 UTC, albertospelta commented on src/Assets/ManageDates/Templates/DateLocalization-03.json
> +      "Iso": "dk",
```suggestion
      "Iso": "da",
```

2022-12-22 13:22 UTC, albertospelta commented on src/Assets/ManageDates/Templates/DateLocalization-04.json
> +      "Iso": "dk",
```suggestion
      "Iso": "da",
```

2022-12-22 13:22 UTC, albertospelta commented on src/Assets/ManageDates/Templates/DateLocalization-05.json
> +      "Iso": "dk",
```suggestion
      "Iso": "da",
```

2022-12-22 13:22 UTC, albertospelta commented on src/Assets/ManageDates/Templates/DateLocalization-06.json
> +      "Iso": "dk",
```suggestion
      "Iso": "da",
```

2022-12-22 13:22 UTC, albertospelta commented on src/Assets/ManageDates/Templates/DateLocalization-07.json
> +      "Iso": "dk",
```suggestion
      "Iso": "da",
```

2022-12-23 08:39 UTC, albertospelta approved these changes

2022-12-23 08:40 UTC, mrSkovgaard commented
Suggestions committed. Merry Christmas :-)

2022-12-23 08:47 UTC, merged

2023-03-21 13:22 UTC, albertospelta commented
Added in version [1.0.2](https://github.com/sql-bi/Bravo/releases/tag/v1.0.2)